#!/usr/bin/env sh

# Inclui o script husky.sh e common.sh a partir do diretório
. "$(dirname -- "$0")/_/husky.sh"
. "$(dirname -- "$0")/common.sh"

### Bloqueio de pushes para branches específicos
# Aviso: isso também deve ser feito no repositório remoto
branch="$(git rev-parse --abbrev-ref HEAD)"

# Bloqueio de push para a branch master
if [ "$branch" = "master" ]; then
	echo "Você não pode fazer commit diretamente na branch master"
	exit 1
fi

# Bloqueio de push para a branch main
if [ "$branch" = "main" ]; then
	echo "Você não pode fazer commit diretamente na branch main"
	exit 1
fi

# Bloqueio de push para a branch dev
if [ "$branch" = "dev" ]; then
	echo "Você não pode fazer commit diretamente na branch dev"
	exit 1
fi
